version: '2'
services:
  mysql_base:
    image: mysql/mysql-server:5.7.14
    mem_limit: 512m
    user: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=pwd_root
    volumes:
    - ./my.cnf:/etc/my.cnf
    - ./init_monolith_db.sql:/etc/init_monolith_db.sql
    - ./init_shared_db.sql:/etc/init_shared_db.sql
    command: [mysqld, --init-file=/etc/init_monolith_db.sql]