FROM adoptopenjdk:8u242-b08-jre-hotspot-bionic

VOLUME ["/kafka"]

RUN apt-get update && apt-get install bash

ENV KAFKA_HOME /kafka_2.11-0.10.0.1

ADD kafka_2.11-0.10.0.1 /opt

CMD /opt/bin/zookeeper-server-start.sh /opt/config/zookeeper.properties

EXPOSE 2181